version: '3'
# sudo docker-compose -f docker-compose-prod.yml up --build
services:
    django:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - ./db:/app/db